---
title: Let's Talk Payments
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: prasad@letstalkpayments.com
description: 
baseurl: 
url: 
twitter_username: 
github_username: 
markdown: kramdown
theme: minima
plugins:
- jekyll-paginate
paginate: 10
excerpt_separator: "<!--more-->"
